### ISSUE TITLE
[Bug] 학교 설정 관련 버그

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio19-5/team11-android#15]
처음 학교 설정을 할 때 서울대학교가 아니면 미리보기가 뜨지 않고 최종 검색을 눌러도 올바른 학교가 아니라고 뜹니다. 서울대학교만 가능한건가요? 그리고 학교 인증 탭이 있던데 현재 인증 거치지 않고서도 모든 기능 다 사용할 수 있는것 처럼 보입니다.

**Comment by esc5221** [comment]
현재 서울대 연세대 고려대만 등록되있어서 그렇습니다..!
