### ISSUE TITLE
Bug: 게시글을 올려도 메인화면 업데이트가 되지 않음

### ISSUE THREAD

**Issue by MinnieMinwoo** [wafflestudio19-5/team11-android#16]
말 그대로 어떤 게시글을 올려도 메인 화면에서 앱 실행시에 처음 올라온 게시글 상태가 유지되는거 같습니다! 메인화면으로 돌아올때마다 네트워크 요청을 다시 보내는 식으로 해서 데이터를 업데이트하는게 좋을거 같네요..!

**Comment by JYPSloth** [comment]
감사합니다. 이 버그는 배포 이후에 해결되었습니다!!
