### ISSUE TITLE
Bug: 이미지를 게시글에 올리려다가 도중에 취소한 경우, 빈 이미지가 올라갑니다.

### ISSUE THREAD

**Issue by HunRotation** [wafflestudio19-5/team11-android#7]
![11조2](https://user-images.githubusercontent.com/48827296/148633891-2a62809d-3607-45f1-b18a-ce30ee5e963c.jpg)

게시글을 작성하는 페이지에서 왼쪽 아래의 버튼을 이용해 이미지를 올리고자 하면, 위 사진과 같이 이미지를 업로드할 앱을 선택하도록 하거나, 이미 default 앱이 설정된 경우 곧바로 이미지 선택 창으로 넘어가게 됩니다.

![11조3](https://user-images.githubusercontent.com/48827296/148633933-4cfa9101-1774-43cc-935a-9f3ada9979f9.jpg)

이 때, 이미지 또는 실행 앱을 선택하지 않고 취소 버튼을 누르게 되면, 위 사진과 같이 내용이 없는 빈 이미지가 게시글에 올라오게 됩니다.

![11조4](https://user-images.githubusercontent.com/48827296/148634128-60b29108-b8a5-499b-87f9-e953ca7de641.jpg)

이 사진을 통해 빈 이미지가 이미 추가되었고, 그 뒤에 이미지 올리기를 다시 시행하면 빈 이미지 뒤에 다른 이미지가 추가되는 것을 알 수 있습니다.

**Comment by JYPSloth** [comment]
헐 ㄷㄷㄷ 게시글 이미지 업로드 기능은 아무래도 몇 시간 전에 급하게 만들었다보니 문제가 좀 있네요 수정하겠습니다!
