### ISSUE TITLE
댓글 UI issue

### ISSUE THREAD

**Issue by Chang-Man** [wafflestudio19-5/team11-android#8]
![KakaoTalk_20220108_162143915](https://user-images.githubusercontent.com/88428193/148635712-6baa201c-2193-4fae-864b-6e527e705dfd.jpg)

댓글 UI가 이렇게 깨지는 문제가 있습니다!

**Comment by JuTaK97** [comment]
다크모드는 아직 미적용입니다!ㅠㅠ 제보 감사합니다.
